# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        OCUserBundle\Entity\User: plaintext


    providers:
        mainprovider:
            entity:
                class:  OCUserBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  mainprovider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /platform
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }